config/routes.rb
Rails.application.routes.draw do

  resources :evaluations
  resources :evaluation_comment_definitions do as_routes end
  resources :evaluation_section_definitions do as_routes end
  resources :evaluation_definitions do as_routes end
  resources :indicator_ratings do as_routes end
  resources :evaluative_indicators do
    member do
      get 'clone_rec'
    end
    as_routes
  end
  resources :indicator_average_definitions do as_routes end
  resources :sub_domains do as_routes end
  resources :domains do as_routes end
  resources :indicator_score_definitions do as_routes end

  root 'home#index'

  get 'home/index'
  get 'home/new_eval'

end

app/models/evaluation.rb
# == Schema Information
#
# Table name: evaluations
#
#  id                       :integer          not null, primary key
#  evaluation_date          :datetime
#  evaluation_definition_id :integer
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#
# Indexes
#
#  index_evaluations_on_evaluation_definition_id  (evaluation_definition_id)
#

class Evaluation < ActiveRecord::Base
  belongs_to :evaluation_definition
  has_many :evaluation_sections, -> { includes(:evaluation_section_definition).order "evaluation_section_definitions.order_index" }, :dependent => :destroy
  accepts_nested_attributes_for :evaluation_sections

  def display_name
    evaluation_definition.definition_name + " : " + id.to_s + "-" + evaluation_date.to_default_s
  end
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  def index
    @evaluation_definitions = EvaluationDefinition.all
    @evaluations = Evaluation.all
  end

  def new
    @eval_def = EvaluationDefinition.find(params[:evaluation_definition_id])
    @evaluation = Evaluation.new
    @evaluation.evaluation_date = Date.today
    @evaluation.evaluation_definition = @eval_def
    @eval_def.evaluation_section_definitions.each do |esd|
      @es = EvaluationSection.new
      @evaluation.evaluation_sections << @es
      @es.evaluation = @evaluation
      @es.evaluation_section_definition = esd
      esd.evaluation_comment_definitions.each do |ecd|
        @ec = EvaluationComment.new
        @es.evaluation_comments << @ec
        @ec.evaluation_comment_definition = ecd
        @ec.evaluation_section = @es
      end
      if !esd.sub_domain.nil?
        esd.sub_domain.evaluative_indicators.each do |ei|
          @ei = EvaluationIndicator.new
          @ei.evaluative_indicator = ei
          @ei.evaluation_section = @es
          @es.evaluation_indicators << @ei
        end
      end
    end
    #@eval.save!
  end

  def create
    @evaluation = Evaluation.new(evaluation_params)
    if @evaluation.save
      redirect_to evaluations_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @evaluation = Evaluation.find(params[:id])
  end

  def update
    @evaluation = Evaluation.find(params[:id])
    if @evaluation.update(evaluation_params)
      redirect_to evaluations_path
    else
      render 'edit'
    end
  end

  def destroy
  end

  private
  def evaluation_params()
    params.require(:evaluation).permit(
        :evaluation_definition_id, :evaluation_date,
        evaluation_sections_attributes:
            [:id, :evaluation_section_definition_id,
             evaluation_comments_attributes: [:id, :evaluation_comment_definition_id, :comment],
             evaluation_indicators_attributes: [:id, :evaluative_indicator_id, :score]])
  end
end

app/helpers/evaluation_helper.rb
module EvaluationHelper
end

app/views/evaluations/_evaluation.html.erb
<%= form_for @evaluation do |e| %>
  <%= e.hidden_field :evaluation_definition_id %>
  <%= e.date_select :evaluation_date %>
  <%= e.fields_for :evaluation_sections do |es_form| %>
    <div class="evaluation-section">
      <%= es_form.hidden_field :evaluation_section_definition_id %>
      <h2><%= es_form.object.evaluation_section_definition.prompt %></h2>
      <%= es_form.fields_for :evaluation_comments do |comment| %>
        <% if comment.object.evaluation_comment_definition.start_of_section %>
          <%= comment.hidden_field :evaluation_comment_definition_id %>
          <h3><%= comment.object.evaluation_comment_definition.prompt %></h3>
          <%= comment.text_area :comment %>
        <% end %>
      <% end %>
      <% if !es_form.object.evaluation_section_definition.sub_domain.nil? %>
        <h4><%= es_form.object.evaluation_section_definition.sub_domain.name %></h4>
        <%= es_form.fields_for :evaluation_indicators do |indicator| %>
          <%= indicator.hidden_field :evaluative_indicator_id %>
          <div>
            <%= indicator.object.evaluative_indicator.name %>
            <%= indicator.text_field :score %>
          </div>
        <% end %>
      <% end %>
      <%= es_form.fields_for :evaluation_comments do |comment| %>
        <% if !comment.object.evaluation_comment_definition.start_of_section %>
          <%= comment.hidden_field :evaluation_comment_definition_id %>
          <h3><%= comment.object.evaluation_comment_definition.prompt %></h3>
          <%= comment.text_area :comment %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <%= e.submit "Create" %>
<% end %>

app/views/evaluations/create.html.erb
<h1>Evaluation#create</h1>
<p>Find me in app/views/evaluation/create.html.erb</p>

app/views/evaluations/edit.html.erb
<h1>Evaluation#edit</h1>
<%= render partial: @evaluation %>

app/views/evaluations/index.html.erb
<h1>Evaluation#index</h1>
<% @evaluation_definitions.each do |evaluation_definition| %>
  <%= link_to "New " + evaluation_definition.definition_name, new_evaluation_path(evaluation_definition_id: evaluation_definition.id) %>
<% end %>
<ul>
  <% @evaluations.each do |evaluation| %>
    <li><%= link_to evaluation.display_name, edit_evaluation_path(evaluation) %></li>
  <% end %>
</ul>

app/views/evaluations/new.html.erb
<%= render @evaluation %>

app/views/evaluations/show.html.erb
<h1>Evaluation#show</h1>
<p>Find me in app/views/evaluation/show.html.erb</p>