config/routes.rb
Rails.application.routes.draw do

  resources :evaluations
  resources :evaluation_comment_definitions do as_routes end
  resources :evaluation_section_definitions do as_routes end
  resources :evaluation_definitions do as_routes end
  resources :indicator_ratings do as_routes end
  resources :evaluative_indicators do
    member do
      get 'clone_rec'
    end
    as_routes
  end
  resources :indicator_average_definitions do as_routes end
  resources :sub_domains do as_routes end
  resources :domains do as_routes end
  resources :indicator_score_definitions do as_routes end

  root 'home#index'

  get 'home/index'
  get 'home/new_eval'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def new_eval
    @eval_def = EvaluationDefinition.find(params[:id])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Simple Eval System</h1>

<p><%=link_to "Domains", domains_path %></p>
<p><%=link_to "Sub Domains", sub_domains_path %></p>
<p><%=link_to "Indicator Score Definitions", indicator_score_definitions_path %></p>
<p><%=link_to "Indicator Average Definitions", indicator_average_definitions_path %></p>
<p><%=link_to "Evaluative Indicators", evaluative_indicators_path %></p>
<p><%=link_to "Evaluation Definitions", evaluation_definitions_path %></p>

app/views/home/new_eval.html.erb
<% @eval_def.evaluation_section_definitions.each do |sec| %>
    <h1><%= sec.prompt %></h1>
    <% sec.evaluation_comment_definitions.select { |cd| cd.start_of_section }.each do |cd| %>
        <h2><%= cd.prompt %></h2>
        <input type="text">
    <% end %>
    <% if !sec.sub_domain.nil? %>
        <% sec.sub_domain.evaluative_indicators.each do |ei| %>
          <p><%= ei.name %></p>
        <% end %>
    <% end %>
<% end %>